// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrzdlrgkxpjcgtxfgzvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyemRscmdreHBqY2d0eGZnenZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjQyNjcsImV4cCI6MjA2NDY0MDI2N30.wCFsL_sSS5m2hIw3hM-5fsP7KYDwPaevnXHnWAhDS7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);